name: Build pytest-tcpclient

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          activate-environment: "true"
      - name: Test with nox
        run: |
            uv pip install nox
            uv run --frozen nox
